In [1]:
import numpy as np
import pandas as pd

In [2]:
#Importing TransferMarkt DF
transfermarkt = pd.read_excel('data/transfermarktFINAL.xlsx')

#Importing English Premier League Data data. The column names were modified by me in MS Excel before importing them here.
england_standard = pd.read_excel('data/league_data/england/england_std.xlsx')
england_shooting = pd.read_excel('data/league_data/england/england_shooting.xlsx')
england_shot_creation = pd.read_excel('data/league_data/england/england_shot_creation.xlsx')
england_possession = pd.read_excel('data/league_data/england/england_possession.xlsx')
england_passing = pd.read_excel('data/league_data/england/england_passing.xlsx')
england_defend = pd.read_excel('data/league_data/england/england_defending.xlsx')
england_misc = pd.read_excel('data/league_data/england/england_misc.xlsx')


#List of Column Names for each dataframe. These column names will be used to rename the columns on the remaining dataframes to be imported.
std_cols = [a for a in england_standard.columns]
shooting_cols = [a for a in england_shooting.columns]
shot_creation_cols = [a for a in england_shot_creation.columns]
possession_cols = [a for a in england_possession.columns]
passing_cols = [a for a in england_passing.columns]
defending_cols = [a for a in england_defend.columns]
misc_cols = [a for a in england_misc.columns]


#Dropping duplicate repeating columns from English Premier League dataframes
england_shooting.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Gls','Matches'],axis=1, inplace=True)
england_shot_creation.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches'],axis=1, inplace=True)
england_possession.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)
england_passing.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)
england_defend.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)
england_misc.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)


#Importing Spanish La Liga data
spain_standard = pd.read_excel('data/league_data/spain/spain_std.xlsx')
spain_standard.columns = std_cols

spain_shooting = pd.read_excel('data/league_data/spain/spain_shooting.xlsx')
spain_shooting.columns = shooting_cols
spain_shooting.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches','Gls'],axis=1, inplace=True)

spain_shot_creation = pd.read_excel('data/league_data/spain/spain_shot_creation.xlsx')
spain_shot_creation.columns = shot_creation_cols
spain_shot_creation.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches'],axis=1, inplace=True)

spain_possession = pd.read_excel('data/league_data/spain/spain_possession.xlsx')
spain_possession.columns = possession_cols
spain_possession.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

spain_passing = pd.read_excel('data/league_data/spain/spain_passing.xlsx')
spain_passing.columns = passing_cols
spain_passing.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

spain_defend = pd.read_excel('data/league_data/spain/spain_defending.xlsx')
spain_defend.columns = defending_cols
spain_defend.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

spain_misc = pd.read_excel('data/league_data/spain/spain_misc.xlsx')
spain_misc.columns = misc_cols
spain_misc.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)


#Importing Italian Serie A data
italy_standard = pd.read_excel('data/league_data/italy/italy_std.xlsx')
italy_standard.columns = std_cols

italy_shooting = pd.read_excel('data/league_data/italy/italy_shooting.xlsx')
italy_shooting.columns = shooting_cols
italy_shooting.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches','Gls'],axis=1, inplace=True)

italy_shot_creation = pd.read_excel('data/league_data/italy/italy_shot_creation.xlsx')
italy_shot_creation.columns = shot_creation_cols
italy_shot_creation.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches'],axis=1, inplace=True)

italy_possession = pd.read_excel('data/league_data/italy/italy_possession.xlsx')
italy_possession.columns = possession_cols
italy_possession.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

italy_passing = pd.read_excel('data/league_data/italy/italy_passing.xlsx')
italy_passing.columns = passing_cols
italy_passing.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

italy_defend = pd.read_excel('data/league_data/italy/italy_defending.xlsx')
italy_defend.columns = defending_cols
italy_defend.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

italy_misc = pd.read_excel('data/league_data/italy/italy_misc.xlsx')
italy_misc.columns = misc_cols
italy_misc.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)


#Importing German Bundesliga data
germany_standard = pd.read_excel('data/league_data/germany/germany_std.xlsx')
germany_standard.columns = std_cols

germany_shooting = pd.read_excel('data/league_data/germany/germany_shooting.xlsx')
germany_shooting.columns = shooting_cols
germany_shooting.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches','Gls'],axis=1, inplace=True)

germany_shot_creation = pd.read_excel('data/league_data/germany/germany_shot_creation.xlsx')
germany_shot_creation.columns = shot_creation_cols
germany_shot_creation.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches'],axis=1, inplace=True)

germany_possession = pd.read_excel('data/league_data/germany/germany_possession.xlsx')
germany_possession.columns = possession_cols
germany_possession.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

germany_passing = pd.read_excel('data/league_data/germany/germany_passing.xlsx')
germany_passing.columns = passing_cols
germany_passing.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

germany_defend = pd.read_excel('data/league_data/germany/germany_defending.xlsx')
germany_defend.columns = defending_cols
germany_defend.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

germany_misc = pd.read_excel('data/league_data/germany/germany_misc.xlsx')
germany_misc.columns = misc_cols
germany_misc.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)


#Importing French Ligue 1 data
france_standard = pd.read_excel('data/league_data/france/france_std.xlsx')
france_standard.columns = std_cols

france_shooting = pd.read_excel('data/league_data/france/france_shooting.xlsx')
france_shooting.columns = shooting_cols
france_shooting.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches','Gls'],axis=1, inplace=True)

france_shot_creation = pd.read_excel('data/league_data/france/france_shot_creation.xlsx')
france_shot_creation.columns = shot_creation_cols
france_shot_creation.drop(['Rk','Player','Squad','Age','Born','90s▼','Nation','Pos','Matches'],axis=1, inplace=True)

france_possession = pd.read_excel('data/league_data/france/france_possession.xlsx')
france_possession.columns = possession_cols
france_possession.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

france_passing = pd.read_excel('data/league_data/france/france_passing.xlsx')
france_passing.columns = passing_cols
france_passing.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

france_defend = pd.read_excel('data/league_data/france/france_defending.xlsx')
france_defend.columns = defending_cols
france_defend.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

france_misc = pd.read_excel('data/league_data/france/france_misc.xlsx')
france_misc.columns = misc_cols
france_misc.drop(['Rk','Player','Squad','Age','Born','90s','Nation','Pos','Matches'],axis=1, inplace=True)

In [3]:
#Making a single dataframe for each league
eng_df = pd.concat([england_standard, england_shooting, england_shot_creation, england_possession, england_passing, england_defend, england_misc],axis=1,join="inner")
esp_df = pd.concat([spain_standard, spain_shooting, spain_shot_creation, spain_possession, spain_passing, spain_defend, spain_misc],axis=1,join="inner")
ita_df = pd.concat([italy_standard, italy_shooting, italy_shot_creation, italy_possession, italy_passing, italy_defend, italy_misc],axis=1,join="inner")
ger_df = pd.concat([germany_standard, germany_shooting, germany_shot_creation, germany_possession, germany_passing, germany_defend, germany_misc],axis=1,join="inner")
fra_df = pd.concat([france_standard, france_shooting, france_shot_creation, france_possession, france_passing, france_defend, france_misc],axis=1,join="inner")

In [4]:
full_df = pd.concat([eng_df,esp_df,ita_df,ger_df,fra_df])

In [5]:
full_df

,Player,Squad,MP,Starts,Min,Total Mins/90,Gls,Ast,Non-Penalty Goals,Penalties Scored,...,Crosses,Interceptions,Tackles Won,Penalty Kicks Won,Penalties Conceded,Own Goals,Total Loose Balls Recovered,Aerial Duel Wons,Aerial Duel Lost,% Aerial Duels Won
0,Pierre Højbjerg,Tottenham,38,38,3420,38.0,2,4,2,0,...,11,49,82,0.0,1.0,0,429.0,52.0,40.0,56.5
1,Hugo Lloris,Tottenham,38,38,3420,38.0,0,0,0,0,...,0,0,0,0.0,0.0,0,152.0,0.0,0.0,NaN
2,Emiliano Martínez,Aston Villa,38,38,3420,38.0,0,0,0,0,...,0,0,0,0.0,0.0,0,178.0,0.0,0.0,NaN
3,Aaron Ramsdale,Sheffield Utd,38,38,3420,38.0,0,0,0,0,...,0,0,0,0.0,1.0,0,183.0,0.0,0.0,NaN
4,Kasper Schmeichel,Leicester City,38,38,3420,38.0,0,0,0,0,...,0,0,0,0.0,0.0,1,161.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,Loïc Bessile,Bordeaux,1,1,90,1.0,0,0,0,0,...,0,0,1,0.0,0.0,0,5.0,3.0,1.0,75.0
495,Marcin Bułka,Paris S-G,1,1,90,1.0,0,0,0,0,...,2,2,1,0.0,0.0,0,10.0,1.0,3.0,25.0
496,Yoann Etienne,Lorient,1,1,90,1.0,0,0,0,0,...,0,0,0,0.0,0.0,0,3.0,0.0,0.0,NaN
497,Radosław Majecki,Monaco,1,1,90,1.0,0,0,0,0,...,0,0,0,0.0,0.0,0,3.0,0.0,0.0,NaN
498,Edouard Mendy,Rennes,1,1,90,1.0,0,0,0,0,...,1,1,0,1.0,0.0,0,11.0,2.0,3.0,40.0

In [6]:
outfield_tm = transfermarkt[transfermarkt['Position']!='Goalkeeper']

In [7]:
final_tm = outfield_tm[outfield_tm['Contract Years Left']!='fail']